platform :ios, '14.0'

use_frameworks!

# Read target package info
require '../../node_modules/@capacitor/ios/scripts/pods_helpers'

target 'App' do
  capacitor_pods
  # यदि आपके पास कोई अन्य कस्टमाइज्ड पॉड्स हैं तो वो यहाँ आ सकते हैं
end
