platform :ios, '14.0'

use_frameworks!

# Capacitor के प्लगइन्स और हेल्पर फंक्शन्स को लोड करने का सही तरीका
def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
end

target 'App' do
  capacitor_pods
end
